name: barwidth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11

  # core scientific stack
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - opencv
  - networkx
  - imageio
  - h5py
  - pillow
  - tifffile

  - pip
  - pip:
    - lazy_loader
    # - your_other_pip_only_package
